services:
  portainer:
    image: 'portainer/portainer-ce'
    container_name: portainer
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - admin-net
    ports:
      - '8000:8000'
      - '9000:9000'
    restart: unless-stopped
  
    
