services:
  registry-srv:
    image: 'registry'
    container_name: registry-srv
    volumes:
      - registry_data:/var/lib/registry
    networks:
      - registry-net
    ports:
      - '5000:5000'
    restart: unless-stopped
  
  registry-web:
    image: 'hyper/docker-registry-web'
    container_name: registry-web
    environment:
      - REGISTRY_URL=http://registry-srv:5000/v2
      - REGISTRY_NAME=localhost:5000
    networks:
       - registry-net
    ports:
      - '8081:8080'
    restart: unless-stopped

