services:
  portainer:
    image: 'portainer/portainer-ce'
    container_name: portainer
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '8000:8000'
      - '9000:9000'
    restart: unless-stopped

  prometheus:
    image: 'prom/prometheus'
    container_name: prometheus
    volumes:
      - prometheus_data:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    restart: unless-stopped

  cadvisor:
    image: 'google/cadvisor'
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
    - '8080:8080'
    restart: unless-stopped

  grafana:
    image: 'grafana/grafana'
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - '3000:3000'
    restart: unless-stopped
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel

  docker_mon:
    image: philhawthorne/ha-dockermon
    container_name: ha_dockermon
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '8126:8126'
    restart: unless-stopped
  
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/custom_components/configuration.yaml:/var/lib/docker/custom_components/configuration.yaml
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '8123:8123'
    restart: unless-stopped

  registry-srv:
    container_name: registry-srv
    image: registry
    volumes:
      - registry_data:/var/lib/registry
    ports:
      - '5000:5000'
    restart: unless-stopped

  registry-web:
    image: hyper/docker-registry-web
    container_name: registry-web
    depends_on:
      - registry-srv
    environment:
      - REGISTRY_URL=http://registry-srv:5000/v2
      - REGISTRY_NAME=localhost:5000
    ports:
      - '8081:8080'

volumes:
  portainer_data:
    external: true
  grafana-storage:
    external: true
  prometheus_data:
    external: true
  registry_data:
    external: true
  
networks:
  default: 
    external:
      name: web-net

