services:
  registry-srv:
    container_name: registry-srv
    image: registry
    volumes:
      - registry_data:/var/lib/registry
    ports:
      - '5000:5000'
    restart: unless-stopped
    networks:
      - registry-net

  registry-web:
    image: hyper/docker-registry-web
    container_name: registry-web
    depends_on:
      - registry-srv
    environment:
      - REGISTRY_URL=http://registry-srv:5000/v2
      - REGISTRY_NAME=localhost:5000
    ports:
      - '8081:8080'
    networks:
      - registry-net

volumes:
  registry_data:
    external: true
